/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract } from 'ethers';

export class IKycDappFactory {
  static connect(address, signerOrProvider) {
    return new Contract(address, _abi, signerOrProvider);
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'from',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'to',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
    ],
    name: 'IdentityTransfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'uint8',
        name: 'level',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'platformIdentifier',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'specialization',
        type: 'bytes32',
      },
    ],
    name: 'KycApplied',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'newKycDetailsIPfS',
        type: 'bytes32',
      },
    ],
    name: 'KycDetailsUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint8',
        name: 'level',
        type: 'uint8',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'platformIdentifier',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'specialization',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'KycFeeUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'uint8',
        name: 'level',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'platformIdentifier',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'specialization',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: 'newKycStatus',
        type: 'uint8',
      },
    ],
    name: 'KycStatusUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'newProfileDetailsIPfS',
        type: 'bytes32',
      },
    ],
    name: 'ProfileDetailsUpdated',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
    ],
    name: 'applyForKyc',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_kycUnapprovedDetailsIPFS',
        type: 'bytes32',
      },
    ],
    name: 'approveKycDetails',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'dayswappers',
    outputs: [
      {
        internalType: 'contract IDayswappers',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_wallet',
        type: 'address',
      },
    ],
    name: 'getIdentityByAddress',
    outputs: [
      {
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'kycApprovedDetailsIPFS',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: 'profileDetailsIPFS',
        type: 'bytes32',
      },
      {
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: 'level1',
        type: 'uint8',
      },
      {
        internalType: 'bool',
        name: 'isGovernanceControllable',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
    ],
    name: 'getIdentityByUsername',
    outputs: [
      {
        internalType: 'bytes32',
        name: 'username',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'kycApprovedDetailsIPFS',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: 'profileDetailsIPFS',
        type: 'bytes32',
      },
      {
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: 'level1',
        type: 'uint8',
      },
      {
        internalType: 'bool',
        name: 'isGovernanceControllable',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
    ],
    name: 'getKycFee',
    outputs: [
      {
        internalType: 'uint256',
        name: '_fee',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_wallet',
        type: 'address',
      },
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
    ],
    name: 'getKycStatusByAddress',
    outputs: [
      {
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
    ],
    name: 'getKycStatusByUsername',
    outputs: [
      {
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    name: 'identities',
    outputs: [
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'kycApprovedDetailsIPFS',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: 'profileDetailsIPFS',
        type: 'bytes32',
      },
      {
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: 'level1',
        type: 'uint8',
      },
      {
        internalType: 'bool',
        name: 'isGovernanceControllable',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: '_newWallet',
        type: 'address',
      },
    ],
    name: 'identityTransfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_wallet',
        type: 'address',
      },
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
    ],
    name: 'isKycApproved',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_wallet',
        type: 'address',
      },
    ],
    name: 'isKycLevel1',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'kycDapp',
    outputs: [
      {
        internalType: 'contract IKycDapp',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nrtManager',
    outputs: [
      {
        internalType: 'contract INRTManager',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'prepaidEs',
    outputs: [
      {
        internalType: 'contract IPrepaidEs',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_kycUnapprovedDetailsIPFS',
        type: 'bytes32',
      },
    ],
    name: 'proposeKycDetails',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'randomnessManager',
    outputs: [
      {
        internalType: 'contract RandomnessManager',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_newUsername',
        type: 'bytes32',
      },
    ],
    name: 'register',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
    ],
    name: 'resolveAddress',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_wallet',
        type: 'address',
      },
    ],
    name: 'resolveUsername',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_wallet',
        type: 'address',
      },
    ],
    name: 'resolveUsernameStrict',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: '_newContract',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: '_isGovernanceControllable',
        type: 'bool',
      },
    ],
    name: 'setIdentityOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'setInitialValues',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_kycDapp',
        type: 'address',
      },
    ],
    name: 'setKycDapp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'timeallyClub',
    outputs: [
      {
        internalType: 'contract ITimeAllyClub',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'timeallyManager',
    outputs: [
      {
        internalType: 'contract ITimeAllyManager',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'timeallyPromotionalBucket',
    outputs: [
      {
        internalType: 'contract ITimeAllyPromotionalBucket',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'updateKycFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '_username',
        type: 'bytes32',
      },
      {
        internalType: 'uint8',
        name: '_level',
        type: 'uint8',
      },
      {
        internalType: 'bytes32',
        name: '_platformIdentifier',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: '_specialization',
        type: 'bytes32',
      },
      {
        internalType: 'enum IKycDapp.KYC_STATUS',
        name: '_kycStatus',
        type: 'uint8',
      },
    ],
    name: 'updateKycStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'usernames',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'validatorManager',
    outputs: [
      {
        internalType: 'contract IValidatorManager',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
